### ISSUE TITLE
version 2.0.2 has a big issue

### ISSUE THREAD

**Issue by xmqywx** [pixolith/fabricjs-customise-controls-extension#73] opened 2019-06-09 16:03 UTC
**Version**: 2.0.2
**Fabricjs**: 2.4.6 ~ 3.1.0
**Macos**

When updated version to 2.0.2, just require this js
Object can not move directly, 
It needs to be selected before it can be moved

**Comment by MDSLKTR** [comment] 2019-06-10 18:08
Hey thanks for reporting this. Could you maybe reproduce the use case in a fiddle or codesandbox in order for me to figure out how your object is configured and what doesn't work. That would help a lot.

**Comment by mbejda** [comment] 2019-06-20 21:15
@MDSLKTR  I just got the same issue. Here is a jsfiddle reproducing it. 
https://jsfiddle.net/b382hnwr/18/
Notice that img drag is initiated on the second click whereas it should have been initiated on the first. 
The problem is with this function
```javascript
     fabric.Canvas.prototype.customiseControls({
        tr: {
          action: 'remove',
          cursor: 'pointer'
        }
      });
```

**Comment by MDSLKTR** [comment] 2019-06-24 14:34
Hey thanks for the fiddle. This might be a regression from another fix. I get the problem now though.

**Comment by mbejda** [comment] 2019-06-25 02:49
@MDSLKTR I fixed it by removing this line here. It seems to be working fine but I'm not sure what the consequences are. 
https://github.com/pixolith/fabricjs-customise-controls-extension/blob/next/dist/customiseControls.js#L502

**Comment by MDSLKTR** [comment] 2019-06-26 13:38
@mbejda @mbejda Please try 2.0.5-beta which has been released just now. Should fix both the regression (preventing instant drag) and still stop instant actions (like delete without select)

**Comment by mbejda** [comment] 2019-06-27 06:59
@MDSLKTR the latest works for me ;)

**Comment by MDSLKTR** [comment] 2019-06-27 07:27
Thanks for the feedback :) I'll go ahead and close this but feel free to open another issue if something isn't working as expected with this fix.

**Closed as completed by MDSLKTR** 2019-06-27 07:27 UTC
Labels: bug
