### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by evolutionjay** [pixolith/fabricjs-customise-controls-extension#37] opened 2017-03-31 07:25 UTC
1

<img width="710" alt="2017-03-31 3 20 31" src="https://cloud.githubusercontent.com/assets/4468540/24540501/14c5ed04-1626-11e7-8d23-944b874d5ba6.png">

2

<img width="463" alt="2017-03-31 3 24 27" src="https://cloud.githubusercontent.com/assets/4468540/24540521/2daab8ea-1626-11e7-9b9a-21dd6fb980b5.png">

> Fabricjs version: ` version: "1.7.9"`

**Comment by MDSLKTR** [comment] 2017-03-31 16:01
Hey there, 
thanks for reporting this.
Sounds like this util is no longer used. Will fix this asap and release a new version.

**Comment by MDSLKTR** [comment] 2017-03-31 20:52
Please try installing the latest version 0.2.4 which should resolve the issue when bundling with webpack. Please let me know.

**Comment by evolutionjay** [comment] 2017-04-01 03:28
@MDSLKTR 
Still  error, Tomorrow I write a demo for you.

**Comment by MDSLKTR** [comment] 2017-04-01 07:27
@evolutionjay that would be great, i tested it in my webpack 2 build process of another project, but of course a demo mirroring your setup will help fix this by a mile.

**Comment by p3ndu** [comment] 2017-07-05 12:01
Hi,

Any update on this? We started getting this error also on our project using fabricjs 1.7.13 and fabricjs-customise-controls 0.3.3

```
core.es5.js:1020 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'degreesToRadians' of undefined
TypeError: Cannot read property 'degreesToRadians' of undefined
    at customiseControls.js:15
    at Object.../../../../fabric-customise-controls/dist/customiseControls.js (customiseControls.js:721)
    at __webpack_require__ (bootstrap 1f2d603…:54)
    at Object.../../../../../src/app/occurrences/investigation-tool/investigation-tool.component.ts (0.chunk.js:3949)
```

How can we get this to work again?

Regards,
Alex

**Comment by MDSLKTR** [comment] 2017-07-12 10:29
Hi,
sorry for the delayed response. I was on holiday till yesterday. I'm quite curious what the problem is here since it works for me in my webpack 2 test environment. I already asked the thread creator to create a demo, so i might need to forward that to you @p3ndu since the topic was basically left for dead before.
Maybe at first your webpack config combined with how you include/import customiseControls in your build might be enough.
Regards,
Simon

**Comment by p3ndu** [comment] 2017-07-12 10:32
Hi @MDSLKTR ,

We got it to work with the "standard" mport:
`import "fabric-customise-controls";`

There was another issue on our side which was causing the IIFE to not be executed.

Regards,
Alex

**Comment by MDSLKTR** [comment] 2017-07-12 10:38
Hi @p3ndu,
thanks for clarifying. That was the way i tried it before too. Glad it works for you now! I'll close this then.

Regards,
Simon

**Closed as completed by MDSLKTR** 2017-07-12 10:38 UTC
Labels: bug

**Comment by khajaamin** [comment] 2019-11-06 10:05
Hello Folks, 
Sorry I am bugging on old and closed issue. I am still getting same issue when  I am using it as recommended. 
in main.js 
> import { Fabric } from 'vue-fabric';
> import 'fabric-customise-controls';


package.json 
>  "fabric-customise-controls": "^2.0.6-beta",
>     "vue": "^2.6.10",
>     "vue-fabric": "^0.1.25",

Please help. 

Thanks
