### ISSUE TITLE
I-Text element behaviour when editing

### ISSUE THREAD

**Issue by simsationX** [pixolith/fabricjs-customise-controls-extension#41] opened 2017-05-15 16:54 UTC
Hi Simon

If I have an I-Text element and I want the box growing to the right when im editing it, I have to set originX and originY to left/top. But then your rotate action does not work properly. If I use originX and originY as center the rotate action works fine, but the editing behaviour in the I-Text is that the text grows from the center, to left and right simultaneously. Is it possible to have both working at the same time? Maybe as a custom action and set the originX to left and call rotate of fabric.js? How can I do this?

Simon

**Comment by MDSLKTR** [comment] 2017-05-15 17:24
Hi Simon,
this is likely not a bug. The way the origin works is just as you described. What you can do though is listen for the text related input events from fabric (https://github.com/kangax/fabric.js/wiki/Working-with-events) and set the orgin to top/left while the user is editing it ( `text:editing:entered`) so the box expands to the right. And when the `text:editing:exited` event is fired as the user exits the input, you can switch back to origin center and the rotation will be around the center again.

Regards,
Simon

**Comment by simsationX** [comment] 2017-05-15 17:32
This is exactly what I tried. If I set origin to top left, then the text element is set to another position. So I have to do something like this for `text:editing:entered`:

```
oldTop = options.target.top;
oldLeft = options.target.left;
options.target.setOriginX('left');
options.target.setOriginY('top');
options.target.setTop(oldTop - options.target.getHeight()/2);
options.target.setLeft(oldLeft - options.target.getWidth()/2);
```

But this won't work if the text element is already rotated. I suppose I have to calculate the position with sin/cos then, but I have no clue for the moment.

**Comment by MDSLKTR** [comment] 2017-05-15 17:58
I'm afraid this is the way to go. If you want to create a small testcase in jsfiddle i'd be willing to chip in a few lines but this is a trial and error thing for me too. Fabric might do some things for you automatically but it seems like you need to take care of offset translation manually.

**Comment by simsationX** [comment] 2017-05-16 15:07
I found in fabricjs doc the property `centeredRotation: true`. If originX and originY is not set as center, you can still rotate around the center then. Why does we have to set the originX and originY to center to use your rotate action properly? It's not possible somehow to write a custom action for rotate which does call the rotate of fabricjs directly and does not use your `_setOriginToCenter`?

**Comment by simsationX** [comment] 2017-05-16 16:19
Okay as a quickfix for me, I commented your `_setOriginToCenter` method out because I don't need that. It overwrites the original one from https://github.com/kangax/fabric.js/blob/master/dist/fabric.js#L10653. What's the purpose of your custom `_setOriginToCenter`?

**Comment by MDSLKTR** [comment] 2017-05-16 18:29
That is a relic from the old days possibly. Let me check that, if its not needed anymore it will be removed.

**Comment by MDSLKTR** [comment] 2017-05-16 18:35
Feel free to pull the latest release and close the issue if resolved. I removed both methods as they are no longer necessary and as you correctly stated problematic.

**Closed as completed** 2017-05-16 20:47 UTC
Labels: bug, question
